name: Backend
on:
  push:
      branches: [ main ]
      
      
jobs:    
  build:
    runs-on: ${{ matrix.os }
    defaults:
      run:
        working-directory: Backend/rust_cocochat/
    strategy:
        max-parallel: 5
        matrix:
          os: [macos-latest, ubuntu-latest, ubuntu-latest]
        fail-fast:
          - os: macos-latest
            TARGET: x86_64-apple-darwin
            COMPILER: cargo
            LINKER: cargo

          - os: ubuntu-latest
            TARGET: armv7-unknown-linux-musleabihf
            COMPILER: arm-linux-gnueabihf-gcc-5
            LINKER: gcc-5-arm-linux-gnueabihf

          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl
            COMPILER: gcc
            LINKER: gcc
        
