name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [windows-latest,ubuntu-latest,windows-2022,x64,arm64,armv8,macos-latest,ubuntu-18.04]
    
    defaults:
      run:
        working-directory: Backend/rust_cocochat/

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'GEGAKE/CocoChat'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Once
      run: echo "Succsessfull"
