name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Backend/rust_cocochat/

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'GEGAKE/CocoChat'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Once
      run: cargo run --verbose
